spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

bot:
  username: ${BOT_USERNAME}
  token: ${BOT_TOKEN}

admin:
  id: {ADMIN_ID}
  tech-id: ${ADMIN_TECH_ID}
  office-id: ${ADMIN_OFFICE_ID}

gpt:
  token: ${GPT_TOKEN}

coupon:
  duration-minutes: 15
  expire-in-days: 30

hello-coupon:
  barcode: ${HELLO_COUPON_BARCODE}

date-coupon:
  barcode: ${DATE_COUPON_BARCODE}

ref-coupon:
  barcode: ${REF_COUPON_BARCODE}

poll:
  active-time-days: 7

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

logging:
  level:
    org.telegram.telegrambots.updatesreceivers.DefaultBotSession: INFO
